# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'selDestination.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QMainWindow, QApplication


class Ui_selDestination(QMainWindow):
    # 변수 정의
    btn_home = None
    tabs = None
    btn_start = None
    
    def __init__(self):
        super().__init__()
        self.setupUi(self)
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(512, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setStyleSheet("background-color: white;\n"
                                         "")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setHorizontalSpacing(4)
        self.gridLayout.setVerticalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        Ui_selDestination.btn_home = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn_home.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn_home.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn_home.setFont(font)
        Ui_selDestination.btn_home.setStyleSheet("background-color: #cfe3ac;\n"
                                                 "margin: 3px;\n"
                                                 "padding: 5px;")
        Ui_selDestination.btn_home.setObjectName("btn_home")
        self.gridLayout.addWidget(Ui_selDestination.btn_home, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet("color: white;")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        Ui_selDestination.btn_emrCall = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn_emrCall.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn_emrCall.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn_emrCall.setFont(font)
        Ui_selDestination.btn_emrCall.setStyleSheet("background-color: #ed6339;\n"
                                                    "color: white;\n"
                                                    "margin: 0 2px;\n"
                                                    "padding: 5px;")
        Ui_selDestination.btn_emrCall.setObjectName("btn_emrCall")
        self.gridLayout.addWidget(Ui_selDestination.btn_emrCall, 3, 3, 1, 1)
        Ui_selDestination.tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.tabs.sizePolicy().hasHeightForWidth())
        Ui_selDestination.tabs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.tabs.setFont(font)
        Ui_selDestination.tabs.setStyleSheet("")
        Ui_selDestination.tabs.setObjectName("tabs")
        self.tab_1f = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_1f.sizePolicy().hasHeightForWidth())
        self.tab_1f.setSizePolicy(sizePolicy)
        self.tab_1f.setObjectName("tab_1f")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_1f)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.map_1f = QtWidgets.QLabel(self.tab_1f)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_1f.sizePolicy().hasHeightForWidth())
        self.map_1f.setSizePolicy(sizePolicy)
        self.map_pixmap = QPixmap("../assets/map_1f.svg")
        self.map_1f.setScaledContents(True)  # QLabel의 크기에 이미지를 맞추도록 설정
        # QPixmap이 설정되었을 때에만 크기 조정
        if not self.map_pixmap.isNull():
            self.map_1f.setPixmap(self.map_pixmap)
            self.map_1f.setFixedSize(160, int(self.map_1f.pixmap().height() * 160 / self.map_1f.pixmap().width()))
        self.map_1f.setText("")
        self.map_1f.setObjectName("map_1f")
        self.gridLayout_2.addWidget(self.map_1f, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.tab_1f)
        self.scrollArea.setStyleSheet("border: none;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 146, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        Ui_selDestination.btn1_1f = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn1_1f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn1_1f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn1_1f.setFont(font)
        Ui_selDestination.btn1_1f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn1_1f.setObjectName("btn1_1f")
        self.verticalLayout.addWidget(Ui_selDestination.btn1_1f)
        Ui_selDestination.btn2_1f = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn2_1f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn2_1f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn2_1f.setFont(font)
        Ui_selDestination.btn2_1f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn2_1f.setObjectName("btn2_1f")
        self.verticalLayout.addWidget(Ui_selDestination.btn2_1f)
        Ui_selDestination.btn3_1f = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn3_1f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn3_1f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn3_1f.setFont(font)
        Ui_selDestination.btn3_1f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn3_1f.setObjectName("btn3_1f")
        self.verticalLayout.addWidget(Ui_selDestination.btn3_1f)
        Ui_selDestination.btn4_1f = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn4_1f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn4_1f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn4_1f.setFont(font)
        Ui_selDestination.btn4_1f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn4_1f.setObjectName("btn4_1f")
        self.verticalLayout.addWidget(Ui_selDestination.btn4_1f)
        Ui_selDestination.btn5_1f = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn5_1f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn5_1f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn5_1f.setFont(font)
        Ui_selDestination.btn5_1f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn5_1f.setObjectName("btn5_1f")
        self.verticalLayout.addWidget(Ui_selDestination.btn5_1f)
        Ui_selDestination.btn6_1f = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn6_1f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn6_1f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn6_1f.setFont(font)
        Ui_selDestination.btn6_1f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn6_1f.setObjectName("btn6_1f")
        self.verticalLayout.addWidget(Ui_selDestination.btn6_1f)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 1, 1, 1)
        Ui_selDestination.tabs.addTab(self.tab_1f, "")
        self.tab_2f = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_2f.sizePolicy().hasHeightForWidth())
        self.tab_2f.setSizePolicy(sizePolicy)
        self.tab_2f.setObjectName("tab_2f")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2f)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.map_2f = QtWidgets.QLabel(self.tab_2f)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_2f.sizePolicy().hasHeightForWidth())
        self.map_2f.setSizePolicy(sizePolicy)
        self.map_pixmap = QPixmap("../assets/map_2f.svg")
        self.map_2f.setScaledContents(True)  # QLabel의 크기에 이미지를 맞추도록 설정
        # QPixmap이 설정되었을 때에만 크기 조정
        if not self.map_pixmap.isNull():
            self.map_2f.setPixmap(self.map_pixmap)
            self.map_2f.setFixedSize(160, int(self.map_2f.pixmap().height() * 160 / self.map_2f.pixmap().width()))
        self.map_2f.setText("")
        self.map_2f.setObjectName("map_2f")
        self.gridLayout_4.addWidget(self.map_2f, 0, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2f)
        self.scrollArea_2.setStyleSheet("border:none;")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 146, 180))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        Ui_selDestination.btn1_2f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn1_2f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn1_2f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn1_2f.setFont(font)
        Ui_selDestination.btn1_2f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn1_2f.setObjectName("btn1_2f")
        self.verticalLayout_2.addWidget(Ui_selDestination.btn1_2f)
        Ui_selDestination.btn2_2f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn2_2f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn2_2f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn2_2f.setFont(font)
        Ui_selDestination.btn2_2f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn2_2f.setObjectName("btn2_2f")
        self.verticalLayout_2.addWidget(Ui_selDestination.btn2_2f)
        Ui_selDestination.btn3_2f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn3_2f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn3_2f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn3_2f.setFont(font)
        Ui_selDestination.btn3_2f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn3_2f.setObjectName("btn3_2f")
        self.verticalLayout_2.addWidget(Ui_selDestination.btn3_2f)
        Ui_selDestination.btn4_2f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn4_2f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn4_2f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn4_2f.setFont(font)
        Ui_selDestination.btn4_2f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn4_2f.setObjectName("btn4_2f")
        self.verticalLayout_2.addWidget(Ui_selDestination.btn4_2f)
        Ui_selDestination.btn5_2f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn5_2f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn5_2f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn5_2f.setFont(font)
        Ui_selDestination.btn5_2f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn5_2f.setObjectName("btn5_2f")
        self.verticalLayout_2.addWidget(Ui_selDestination.btn5_2f)
        Ui_selDestination.btn6_2f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn6_2f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn6_2f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn6_2f.setFont(font)
        Ui_selDestination.btn6_2f.setStyleSheet("""
                        background-color: #cfe3ac;
                        text-align: left;
                        padding: 5px;
                        padding-left: 20px;
                        border: none;
                    """)
        Ui_selDestination.btn6_2f.setObjectName("btn6_2f")
        self.verticalLayout_2.addWidget(Ui_selDestination.btn6_2f)
        Ui_selDestination.btn7_2f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn7_2f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn7_2f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn7_2f.setFont(font)
        Ui_selDestination.btn7_2f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn7_2f.setObjectName("btn7_2f")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.addWidget(self.scrollArea_2, 0, 1, 1, 1)
        Ui_selDestination.tabs.addTab(self.tab_2f, "")
        self.tab_3f = QtWidgets.QWidget()
        self.tab_3f.setObjectName("tab_3f")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3f)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.map_3f = QtWidgets.QLabel(self.tab_3f)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_3f.sizePolicy().hasHeightForWidth())
        self.map_3f.setSizePolicy(sizePolicy)
        self.map_pixmap = QPixmap("../assets/map_3f.svg")
        self.map_3f.setScaledContents(True)  # QLabel의 크기에 이미지를 맞추도록 설정
        # QPixmap이 설정되었을 때에만 크기 조정
        if not self.map_pixmap.isNull():
            self.map_3f.setPixmap(self.map_pixmap)
            self.map_3f.setFixedSize(160, int(self.map_3f.pixmap().height() * 160 / self.map_3f.pixmap().width()))
        self.map_3f.setText("")
        self.map_3f.setObjectName("map_3f")
        self.gridLayout_5.addWidget(self.map_3f, 0, 0, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_3f)
        self.scrollArea_3.setStyleSheet("border:none;")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 146, 180))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        Ui_selDestination.btn1_3f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn1_3f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn1_3f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn1_3f.setFont(font)
        Ui_selDestination.btn1_3f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn1_3f.setObjectName("btn1_3f")
        self.verticalLayout_3.addWidget(Ui_selDestination.btn1_3f)
        Ui_selDestination.btn2_3f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn2_3f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn2_3f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn2_3f.setFont(font)
        Ui_selDestination.btn2_3f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn2_3f.setObjectName("btn2_3f")
        self.verticalLayout_3.addWidget(Ui_selDestination.btn2_3f)
        Ui_selDestination.btn3_3f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn3_3f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn3_3f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn3_3f.setFont(font)
        Ui_selDestination.btn3_3f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn3_3f.setObjectName("btn3_3f")
        self.verticalLayout_3.addWidget(Ui_selDestination.btn3_3f)
        Ui_selDestination.btn4_3f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn4_3f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn4_3f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn4_3f.setFont(font)
        Ui_selDestination.btn4_3f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn4_3f.setObjectName("btn4_3f")
        self.verticalLayout_3.addWidget(Ui_selDestination.btn4_3f)
        Ui_selDestination.btn5_3f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn5_3f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn5_3f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn5_3f.setFont(font)
        Ui_selDestination.btn5_3f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn5_3f.setObjectName("btn5_3f")
        self.verticalLayout_3.addWidget(Ui_selDestination.btn5_3f)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_5.addWidget(self.scrollArea_3, 0, 1, 1, 1)
        Ui_selDestination.tabs.addTab(self.tab_3f, "")
        self.tab_4f = QtWidgets.QWidget()
        self.tab_4f.setObjectName("tab_4f")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4f)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.map_4f = QtWidgets.QLabel(self.tab_4f)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_4f.sizePolicy().hasHeightForWidth())
        self.map_4f.setSizePolicy(sizePolicy)
        self.map_pixmap = QPixmap("../assets/map_4f.svg")
        self.map_4f.setScaledContents(True)  # QLabel의 크기에 이미지를 맞추도록 설정
        # QPixmap이 설정되었을 때에만 크기 조정
        if not self.map_pixmap.isNull():
            self.map_4f.setPixmap(self.map_pixmap)
            self.map_4f.setFixedSize(160, int(self.map_4f.pixmap().height() * 160 / self.map_4f.pixmap().width()))
        
        self.map_4f.setText("")
        self.map_4f.setObjectName("map_4f")
        self.gridLayout_6.addWidget(self.map_4f, 0, 0, 1, 1)
        self.scrollArea_4 = QtWidgets.QScrollArea(self.tab_4f)
        self.scrollArea_4.setStyleSheet("border:none;")
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 146, 180))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        Ui_selDestination.btn1_4f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn1_4f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn1_4f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn1_4f.setFont(font)
        Ui_selDestination.btn1_4f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn1_4f.setObjectName("btn1_4f")
        self.verticalLayout_4.addWidget(Ui_selDestination.btn1_4f)
        Ui_selDestination.btn2_4f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn2_4f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn2_4f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn2_4f.setFont(font)
        Ui_selDestination.btn2_4f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn2_4f.setObjectName("btn2_4f")
        self.verticalLayout_4.addWidget(Ui_selDestination.btn2_4f)
        Ui_selDestination.btn3_4f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn3_4f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn3_4f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn3_4f.setFont(font)
        Ui_selDestination.btn3_4f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn3_4f.setObjectName("btn3_4f")
        self.verticalLayout_4.addWidget(Ui_selDestination.btn3_4f)
        Ui_selDestination.btn4_4f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn4_4f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn4_4f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn4_4f.setFont(font)
        Ui_selDestination.btn4_4f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn4_4f.setObjectName("btn4_4f")
        self.verticalLayout_4.addWidget(Ui_selDestination.btn4_4f)
        
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_6.addWidget(self.scrollArea_4, 0, 1, 1, 1)
        Ui_selDestination.tabs.addTab(self.tab_4f, "")
        self.tab_5f = QtWidgets.QWidget()
        self.tab_5f.setObjectName("tab_5f")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_5f)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.map_5f = QtWidgets.QLabel(self.tab_5f)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_5f.sizePolicy().hasHeightForWidth())
        self.map_5f.setSizePolicy(sizePolicy)
        self.map_pixmap = QPixmap("../assets/map_5f.svg")
        self.map_5f.setScaledContents(True)  # QLabel의 크기에 이미지를 맞추도록 설정
        # QPixmap이 설정되었을 때에만 크기 조정
        if not self.map_pixmap.isNull():
            self.map_5f.setPixmap(self.map_pixmap)
            self.map_5f.setFixedSize(160, int(self.map_5f.pixmap().height() * 160 / self.map_5f.pixmap().width()))
        
        self.map_5f.setText("")
        self.map_5f.setObjectName("map_5f")
        self.gridLayout_7.addWidget(self.map_5f, 0, 0, 1, 1)
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab_5f)
        self.scrollArea_5.setStyleSheet("border:none;")
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 146, 180))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        Ui_selDestination.btn1_5f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn1_5f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn1_5f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn1_5f.setFont(font)
        Ui_selDestination.btn1_5f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn1_5f.setObjectName("btn1_5f")
        self.verticalLayout_5.addWidget(Ui_selDestination.btn1_5f)
        Ui_selDestination.btn2_5f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn2_5f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn2_5f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn2_5f.setFont(font)
        Ui_selDestination.btn2_5f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn2_5f.setObjectName("btn2_5f")
        self.verticalLayout_5.addWidget(Ui_selDestination.btn2_5f)
        Ui_selDestination.btn3_5f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn3_5f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn3_5f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn3_5f.setFont(font)
        Ui_selDestination.btn3_5f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn3_5f.setObjectName("btn3_5f")
        self.verticalLayout_5.addWidget(Ui_selDestination.btn3_5f)
        Ui_selDestination.btn4_5f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn4_5f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn4_5f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn4_5f.setFont(font)
        Ui_selDestination.btn4_5f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn4_5f.setObjectName("btn4_5f")
        self.verticalLayout_5.addWidget(Ui_selDestination.btn4_5f)
        Ui_selDestination.btn5_5f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn5_5f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn5_5f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn5_5f.setFont(font)
        Ui_selDestination.btn5_5f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn5_5f.setObjectName("btn5_5f")
        self.verticalLayout_5.addWidget(Ui_selDestination.btn5_5f)
        Ui_selDestination.btn6_5f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn6_5f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn6_5f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn6_5f.setFont(font)
        Ui_selDestination.btn6_5f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn6_5f.setObjectName("btn6_5f")
        self.verticalLayout_5.addWidget(Ui_selDestination.btn6_5f)
        Ui_selDestination.btn7_5f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn7_5f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn7_5f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn7_5f.setFont(font)
        Ui_selDestination.btn7_5f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn7_5f.setObjectName("btn7_5f")
        self.verticalLayout_5.addWidget(Ui_selDestination.btn7_5f)
        Ui_selDestination.btn8_5f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn8_5f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn8_5f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn8_5f.setFont(font)
        Ui_selDestination.btn8_5f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn8_5f.setObjectName("btn8_5f")
        self.verticalLayout_5.addWidget(Ui_selDestination.btn8_5f)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_7.addWidget(self.scrollArea_5, 0, 1, 1, 1)
        Ui_selDestination.tabs.addTab(self.tab_5f, "")
        self.tab_6f = QtWidgets.QWidget()
        self.tab_6f.setObjectName("tab_6f")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_6f)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.map_6f = QtWidgets.QLabel(self.tab_6f)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_6f.sizePolicy().hasHeightForWidth())
        self.map_6f.setSizePolicy(sizePolicy)
        self.map_pixmap = QPixmap("../assets/map_6f.svg")
        self.map_6f.setScaledContents(True)  # QLabel의 크기에 이미지를 맞추도록 설정
        # QPixmap이 설정되었을 때에만 크기 조정
        if not self.map_pixmap.isNull():
            self.map_6f.setPixmap(self.map_pixmap)
            self.map_6f.setFixedSize(160, int(self.map_6f.pixmap().height() * 160 / self.map_6f.pixmap().width()))
        
        self.map_6f.setText("")
        self.map_6f.setObjectName("map_6f")
        self.gridLayout_8.addWidget(self.map_6f, 0, 0, 1, 1)
        self.scrollArea_6 = QtWidgets.QScrollArea(self.tab_6f)
        self.scrollArea_6.setStyleSheet("border:none;")
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 146, 180))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        Ui_selDestination.btn1_6f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn1_6f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn1_6f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn1_6f.setFont(font)
        Ui_selDestination.btn1_6f.setStyleSheet("background-color: #cfe3ac;\n"
                                                "padding: 2px;\n"
                                                "text-align: left;\n"
                                                "border: none;")
        Ui_selDestination.btn1_6f.setObjectName("btn1_6f")
        self.verticalLayout_6.addWidget(Ui_selDestination.btn1_6f)
        Ui_selDestination.btn2_6f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn2_6f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn2_6f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn2_6f.setFont(font)
        Ui_selDestination.btn2_6f.setStyleSheet("background-color: #cfe3ac;\n"
                                                "padding: 2px;\n"
                                                "text-align: left;\n"
                                                "border: none;")
        Ui_selDestination.btn2_6f.setObjectName("btn2_6f")
        self.verticalLayout_6.addWidget(Ui_selDestination.btn2_6f)
        Ui_selDestination.btn3_6f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn3_6f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn3_6f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn3_6f.setFont(font)
        Ui_selDestination.btn3_6f.setStyleSheet("background-color: #cfe3ac;\n"
                                                "padding: 2px;\n"
                                                "text-align: left;\n"
                                                "border: none;")
        Ui_selDestination.btn3_6f.setObjectName("btn3_6f")
        self.verticalLayout_6.addWidget(Ui_selDestination.btn3_6f)
        Ui_selDestination.btn4_6f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn4_6f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn4_6f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn4_6f.setFont(font)
        Ui_selDestination.btn4_6f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn4_6f.setObjectName("btn4_6f")
        self.verticalLayout_6.addWidget(Ui_selDestination.btn4_6f)
        Ui_selDestination.btn5_6f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn5_6f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn5_6f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn5_6f.setFont(font)
        Ui_selDestination.btn5_6f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn5_6f.setObjectName("btn5_6f")
        self.verticalLayout_6.addWidget(Ui_selDestination.btn5_6f)
        Ui_selDestination.btn6_6f = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn6_6f.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn6_6f.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn6_6f.setFont(font)
        Ui_selDestination.btn6_6f.setStyleSheet("""
                background-color: #cfe3ac;
                text-align: left;
                padding: 5px;
                padding-left: 20px;
                border: none;
            """)
        Ui_selDestination.btn6_6f.setObjectName("btn6_6f")
        self.verticalLayout_6.addWidget(Ui_selDestination.btn6_6f)
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout_8.addWidget(self.scrollArea_6, 0, 1, 1, 1)
        Ui_selDestination.tabs.addTab(self.tab_6f, "")
        self.gridLayout.addWidget(Ui_selDestination.tabs, 2, 1, 1, 2)
        self.title = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.gridLayout.addWidget(self.title, 1, 1, 1, 2)
        Ui_selDestination.btn_start = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ui_selDestination.btn_start.sizePolicy().hasHeightForWidth())
        Ui_selDestination.btn_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        Ui_selDestination.btn_start.setFont(font)
        Ui_selDestination.btn_start.setStyleSheet("background-color: #a1c464;\n"
                                                  "margin: 2px;\n"
                                                  "padding: 5px;")
        Ui_selDestination.btn_start.setObjectName("btn_start")
        self.gridLayout.addWidget(Ui_selDestination.btn_start, 3, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("color: white;\n"
                                   "")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 1, 1, 2)
        self.gridLayout.setColumnStretch(2, 5)
        self.gridLayout.setRowStretch(2, 5)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.retranslateUi(MainWindow)
        Ui_selDestination.tabs.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        Ui_selDestination.btn_home.setText(_translate("MainWindow", " HOME "))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        Ui_selDestination.btn_emrCall.setText(_translate("MainWindow", "긴급호출"))
        Ui_selDestination.btn1_1f.setText(_translate("MainWindow", "CT촬영실"))
        Ui_selDestination.btn2_1f.setText(_translate("MainWindow", "응급의료센터"))
        Ui_selDestination.btn3_1f.setText(_translate("MainWindow", "이비인후과"))
        Ui_selDestination.btn4_1f.setText(_translate("MainWindow", "접수처"))
        Ui_selDestination.btn5_1f.setText(_translate("MainWindow", "치과"))
        Ui_selDestination.btn6_1f.setText(_translate("MainWindow", "화장실"))
        Ui_selDestination.tabs.setTabText(Ui_selDestination.tabs.indexOf(self.tab_1f),
                                          _translate("MainWindow", "     1층     "))
        Ui_selDestination.btn1_2f.setText(_translate("MainWindow", "PET센터"))
        Ui_selDestination.btn2_2f.setText(_translate("MainWindow", "골다공증 검사실"))
        Ui_selDestination.btn3_2f.setText(_translate("MainWindow", "산부인과"))
        Ui_selDestination.btn4_2f.setText(_translate("MainWindow", "초음파실"))
        Ui_selDestination.btn5_2f.setText(_translate("MainWindow", "체외충격파 쇄설실"))
        Ui_selDestination.btn6_2f.setText(_translate("MainWindow", "핵의학과"))
        Ui_selDestination.btn7_2f.setText(_translate("MainWindow", "화장실"))
        Ui_selDestination.tabs.setTabText(Ui_selDestination.tabs.indexOf(self.tab_2f),
                                          _translate("MainWindow", "     2층     "))
        Ui_selDestination.btn1_3f.setText(_translate("MainWindow", "암센터 상담실"))
        Ui_selDestination.btn2_3f.setText(_translate("MainWindow", "영상의학과"))
        Ui_selDestination.btn3_3f.setText(_translate("MainWindow", "응급의료센터"))
        Ui_selDestination.btn4_3f.setText(_translate("MainWindow", "정형외과"))
        Ui_selDestination.btn5_3f.setText(_translate("MainWindow", "화장실"))
        Ui_selDestination.tabs.setTabText(Ui_selDestination.tabs.indexOf(self.tab_3f),
                                          _translate("MainWindow", "     3층     "))
        Ui_selDestination.btn1_4f.setText(_translate("MainWindow", "검진검사실"))
        Ui_selDestination.btn2_4f.setText(_translate("MainWindow", "국제진료센터"))
        Ui_selDestination.btn3_4f.setText(_translate("MainWindow", "종합검진센터"))
        Ui_selDestination.btn4_4f.setText(_translate("MainWindow", "화장실"))
        Ui_selDestination.tabs.setTabText(Ui_selDestination.tabs.indexOf(self.tab_4f),
                                          _translate("MainWindow", "     4층     "))
        Ui_selDestination.btn1_5f.setText(_translate("MainWindow", "가정의학과"))
        Ui_selDestination.btn2_5f.setText(_translate("MainWindow", "뇌혈류검사실"))
        Ui_selDestination.btn3_5f.setText(_translate("MainWindow", "맞춤형비만치료센터"))
        Ui_selDestination.btn4_5f.setText(_translate("MainWindow", "심장내과"))
        Ui_selDestination.btn5_5f.setText(_translate("MainWindow", "암센터"))
        Ui_selDestination.btn6_5f.setText(_translate("MainWindow", "호흡기알레르기내과"))
        Ui_selDestination.btn7_5f.setText(_translate("MainWindow", "호흡기알레르기검진센터"))
        Ui_selDestination.btn8_5f.setText(_translate("MainWindow", "흉부외과"))
        Ui_selDestination.tabs.setTabText(Ui_selDestination.tabs.indexOf(self.tab_5f),
                                          _translate("MainWindow", "     5층     "))
        Ui_selDestination.btn1_6f.setText(_translate("MainWindow", "당뇨상담실"))
        Ui_selDestination.btn2_6f.setText(_translate("MainWindow", "복약지도실"))
        Ui_selDestination.btn3_6f.setText(_translate("MainWindow", "신장내과"))
        Ui_selDestination.btn4_6f.setText(_translate("MainWindow", "성형외과"))
        Ui_selDestination.btn5_6f.setText(_translate("MainWindow", "피부과"))
        Ui_selDestination.btn6_6f.setText(_translate("MainWindow", "화장실"))
        Ui_selDestination.tabs.setTabText(Ui_selDestination.tabs.indexOf(self.tab_6f),
                                          _translate("MainWindow", "     6층     "))
        self.title.setText(_translate("MainWindow", "목적지 설정"))
        Ui_selDestination.btn_start.setText(_translate("MainWindow", "주행시작"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))


